# Generated by Django 4.2.1 on 2024-01-15 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, validators=[django.core.validators.RegexValidator('^[\\w-]+$', message='This field must only contain letters, numbers, hyphens, and underscores.')]),
        ),
    ]
