# Generated by Django 4.2.1 on 2024-01-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_alter_bucket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='events',
        ),
    ]
