# Generated by Django 4.2.1 on 2024-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=30)),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
