# Generated by Django 4.2.1 on 2024-01-16 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_remove_bucket_events'),
        ('events', '0002_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='buckets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucket'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bab83785-2d6e-4c77-940c-7f831b285f6f'), editable=False, unique=True),
        ),
    ]
