# Generated by Django 4.2.1 on 2024-01-16 00:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_remove_bucket_events'),
        ('events', '0003_event_buckets_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='buckets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='buckets.bucket'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c1455c33-258d-4f98-9e5a-11bf63de5466'), editable=False, unique=True),
        ),
    ]
