# Generated by Django 4.2.1 on 2024-01-16 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_remove_bucket_events'),
        ('events', '0005_remove_event_buckets_event_bucket_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to='buckets.bucket'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5f5ab1e2-93ef-4dab-ac16-e6ef42737e91'), editable=False, unique=True),
        ),
    ]
