# Generated by Django 4.2.1 on 2024-01-16 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_remove_bucket_events'),
        ('events', '0006_alter_event_bucket_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='buckets.bucket'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9c28c0bd-0753-4680-9595-34ec36e47479'), editable=False, unique=True),
        ),
    ]
