# Generated by Django 4.2.1 on 2024-01-16 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_bucket_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e401efec-e001-4fca-8d97-6709c37a529d'), editable=False, unique=True),
        ),
    ]
